{% set name = "jupyverse-api" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyverse_api-{{ version }}.tar.gz
  sha256: a93acc93a27890c5c21c218fd51e20fcda557054d25a19b9938d257660d745a5

build:
  noarch: python
  number: 0
  entry_points:
    - jupyverse = jupyverse_api.cli:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - importlib-metadata >=3.6
    - pydantic >=2,<3
    - fastapi-core >=0.95.0,<1
    - fps >=0.4.0,<0.5.0
    - anyio >=3.6.2,<5.0.0

test:
  imports:
    - jupyverse_api
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/jupyverse_api
  summary: The public API for Jupyverse
  keywords: jupyter, server, fastapi
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/jupyverse_api
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
