{% set name = "jupyverse-api" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyverse_api-{{ version }}.tar.gz
  sha256: 2f1a8fa3d3d0f8423b862a4156d67ae546212aea3dc495c172489f7e5a364854

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - pydantic >=1.10.6,<2
    - fastapi >=0.95.0,<1

test:
  imports:
    - jupyverse_api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/jupyverse_api
  summary: The public API for Jupyverse
  keywords: jupyter, server, fastapi
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/jupyverse_api
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
