{% set name = "jupyverse-api" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyverse_api-{{ version }}.tar.gz
  sha256: 32fb571d5156f53e35367c2ca9d2555b9927b6ef1a8bf4a44f481aae4e97bcff

build:
  noarch: python
  number: 0
  entry_points:
    - jupyverse = jupyverse_api.cli:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - pydantic >=2,<3
    - fastapi >=0.95.0,<1
    - rich-click >=1.6.1,<2
    - fps >=0.1.1,<0.2.0

test:
  imports:
    - jupyverse_api
  commands:
    - jupyverse --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/jupyverse_api
  summary: The public API for Jupyverse
  keywords: jupyter, server, fastapi
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/jupyverse_api
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
