schema_version: 1

context:
  version: "0.14.0"

package:
  name: jupyverse-api
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/j/jupyverse-api/jupyverse_api-${{ version }}.tar.gz
    sha256: dab0e36cb007e26aea27a0462978950eb66534f0e2572351e7456c8be3db21c1

build:
  noarch: python
  number: 1
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - jupyverse = jupyverse_api.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build
  run:
    - python >=${{ python_min }}
    - pydantic >=2,<3
    - fastapi-core >=0.95.0,<1
    - fps >=0.6.0,<0.7.0
    - anyio >=4.12.1,<5.0.0
    - anyioutils >=0.7.4
    - pycrdt >=0.12.46,<0.13.0
    - httpx
    - httpx-ws

tests:
  - python:
      imports: jupyverse_api
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: BSD-3-Clause
  license_file: COPYING.md
  homepage: https://github.com/jupyter-server/jupyverse/tree/main/jupyverse_api
  summary: The public API for Jupyverse.

extra:
  recipe-maintainers:
    - davidbrochart
