schema_version: 1

context:
  version: "0.15.3"

package:
  name: jupyverse-api
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/j/jupyverse-api/jupyverse_api-${{ version }}.tar.gz
    sha256: 4ba1f222b5ac87b3523223b8423f6fbce38d7e0d09b5e4c94d8b9b9137be419b

build:
  noarch: python
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - jupyverse = jupyverse_api.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build >=0.11.32,<0.12
  run:
    - python >=${{ python_min }}
    - anyio >=4.12.1,<5.0.0
    - fastapi-core >=0.95.0,<1.0.0,!=0.137.0,!=0.137.1
    - fps >=0.6.3,<0.7.0
    - structlog
    - packaging >=26.2,<27
    - pydantic >=2,<3

tests:
  - python:
      imports: jupyverse_api
  - requirements:
      run:
        - python ${{ python_min }}.*
        - rich-click
        - pip
    script:
      - pip check
      - jupyverse --help

about:
  license: BSD-3-Clause
  license_file: COPYING.md
  homepage: https://github.com/jupyter-server/jupyverse/tree/main/api/api
  summary: The API for Jupyverse.

extra:
  recipe-maintainers:
    - davidbrochart
