schema_version: 1

context:
  version: "0.14.1"

package:
  name: jupyverse-api
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/j/jupyverse-api/jupyverse_api-${{ version }}.tar.gz
    sha256: e8a90f02fd443efc0273b014a2a2fc9b3912fd3be48f613825f2817eaf53f9b5

build:
  noarch: python
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - jupyverse = jupyverse_api.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build
  run:
    - python >=${{ python_min }}
    - pydantic >=2,<3
    - fastapi-core >=0.95.0,<1
    - fps >=0.6.0,<0.7.0
    - anyio >=4.12.1,<5.0.0
    - anyioutils >=0.7.4
    - pycrdt >=0.12.46,<0.13.0
    - httpx
    - httpx-ws

tests:
  - python:
      imports:
        - jupyverse_api
  - requirements:
      run:
        - python ${{ python_min }}.*
        - rich-click
        - pip
    script:
      - pip check
      - jupyverse --help

about:
  license: BSD-3-Clause
  license_file: COPYING.md
  homepage: https://github.com/jupyter-server/jupyverse/tree/main/jupyverse_api
  summary: The public API for Jupyverse.

extra:
  recipe-maintainers:
    - davidbrochart
